from dataclasses import dataclass
from datetime import datetime
from typing import Optional

@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    timestamp: datetime
    direction: int  # 1 for buy, -1 for sell
    size: int
    price: float
    reason: str 